name: deploy
on:
  pull_request:
    branches:
      - main
  pull_request_target:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: commit-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Website preview for commit ${GITHUB_SHA} at ${GITHUB_RUN_ATTEMPT}
            - [Source code](https://github.com/dext7r/commit-comment)
